# Generated by Django 3.1.1 on 2020-12-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201005_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='player',
            field=models.CharField(max_length=30),
        ),
    ]
